todo_app/urls.py
from ast import pattern
from django.contrib import admin
admin.autodiscover()
from django.urls import path, re_path
from . import views

app_name = 'todo_app'

urlpatterns = [
    re_path(r'^$', views.home, name='home'),
    re_path(r'^task-detail/(?P<slug>[-\w]+)/$',views.show_task, name='task_detail'),
    path('change-status/(?P<slug>[-\w]+)/', views.change_status, name='change_status'),
]

todo_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo_app.urls')),
]

todo_app/models.py
from django.contrib.auth.models import User
from itertools import product
from tkinter import CASCADE
from django.db import models
from django.urls import reverse
from django.utils import timezone

# Create your models here.
def one_week_hence():
    return timezone.now() + timezone.timedelta(days=7)
STATUS_CHOICES = (
    ('Pending', 'Pending'),
    ('Completed', 'Completed'),
)


class TodoItem(models.Model):
    todo_id = models.CharField(max_length=50)
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True,help_text='Unique value for product page URL, created from title.')
    description = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    due_date = models.DateTimeField(default=one_week_hence)
    status = models.CharField(choices=STATUS_CHOICES, max_length=50, default='Pending')

    class Meta:
        db_table = 'Todo_items'
        ordering = ['date_added', 'status']

    def __str__(self) -> str:
        return self.title    

    def __unicode__(self):
        return self.title

todo_app/forms.py
from cProfile import label
from django import forms


    
class AddNewForm(forms.Form):
    title = forms.CharField(label="Title", required=True)
    description = forms.CharField(label="Description", widget=forms.Textarea(attrs={'class':'description', 'cols': '20', 'rows': '6'}))
    due_date = forms.DateField(label="Due Date", widget=forms.DateTimeInput(attrs={'type':'date'}))
    #override the default __init__ so we can set the request

    def __init__(self,request=None,*args, **kwargs):
        self.request = request
        super(AddNewForm, self).__init__(*args,**kwargs)

    #custom validation to check for cookies
    def clean(self):
        if self.request:
            if not self.request.session.test_cookie_worked():
                raise forms.ValidationError("Cookies must be enabled.")
            return self.cleaned_data

todo_app/views.py
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from todo_app.forms import AddNewForm
from todo_app.models import TodoItem
from todo_app import action
from todo_project import settings
# Create your views here.


def home(request):
    #getting the total number of our tasks
    completed_list = TodoItem.objects.filter(status="Completed", todo_id=action._todo_id(request))
    pending_list = TodoItem.objects.filter(status="Pending", todo_id=action._todo_id(request))
    todo_item_count = action.todo_distinct_item_count(request)
    page_title='Todo List'
    tasks = action.get_todo_items(request)
    if request.method=="POST":
        #add to action...create the bound form
        postdata = request.POST.copy()
        
        form = AddNewForm(request, postdata)
        #check if posted data is valid
        if form.is_valid():
        #add to action and redirect to action page
            action.add_to_todo(request)
            #if test cookie worked, get rid of it
            if request.session.test_cookie_worked():
                request.session.delete_test_cookie()
    else:
        #it's a GET, create the unbound form.note request as a kwarg
        form = AddNewForm(request=request, label_suffix=':')
    #set the test cookie on our first GET request
    request.session.set_test_cookie()
    return render(request,'index.html',{'pending_list':pending_list, 'completed_list':completed_list, 'form':form, 'todo_item_count':todo_item_count,'tasks':tasks,'page_title':page_title})

def show_task(request, slug):
    task=TodoItem.objects.get(slug=slug)
    page_title = task.name
    todo_item_count = action.todo_distinct_item_count(request)
    tasks = action.get_todo_items(request)
    #getting related products
    # need to evaluate the HTTP method
    if request.method=="POST":
        #add to action...create the bound form
        postdata = request.POST.copy()
        if postdata['submit'] == 'Remove':
            action.remove_from_todo(request)
            return redirect('todo_app:home')
        if postdata['submit'] == 'Update':
            action.update_todo(request)
            return redirect('todo_app:home')
    return render(request,'task.html',{'todo_item_count':todo_item_count,'tasks':tasks,'task':task,'page_title':page_title})

def change_status(request, slug):
    task=TodoItem.objects.get(slug=slug)
    page_title = task.name
    todo_item_count = action.todo_distinct_item_count(request)
    tasks = action.get_todo_items(request)
    #getting related products
    # need to evaluate the HTTP method
    if request.method=="POST":
        #add to action...create the bound form
        postdata = request.POST.copy()
        if postdata['submit'] == 'Completed':
            item_id = postdata['item_id']
            todo_item=TodoItem.objects.get(id=item_id)
            if todo_item:
                todo_item.status = "Completed"
                todo_item.save()
    return redirect('todo_app:home')

templates/base.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DID XHTML 1.0 Strict//EN" "XHTML-s.dtd" >
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <link rel="Stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>
            {% block title %}{% if page_title %}{{ page_title }} - {% endif %}
            {{site_name}} {% endblock %} 
        </title>
        <meta name="Keywords" content="{{meta_keywords}}" />
        <meta name="description" content="{{meta_description}}" />
    </head>
    <body>
        {% block site_wrapper %}{% endblock %}
    </body>
</html>

templates/index.html
{% extends "base.html" %}
{% block site_wrapper %}
{% include "navbar.html" %}
<div class="main">
    <table class="content">
        <thead>
            <th><h1>Due Date</h1></td>
            <hr>
            <th><h1>Task</h1></td>
            <hr>
        </thead>
        <tbody>
        {% for task in tasks %}
            <tr>
                <td>
                    <p>
                        {% if task.status == "Completed" %}
                        <input type="checkbox" name="submit" value="Mark" checked/>
                        {% else %}
                        <input type="checkbox" name="submit" value="Mark"/>
                        {% endif %}
                        {{ task.due_date }}
                    </p><hr>
                </td>
                <td class="each_task">
                    <a href="{% url 'todo_app:task_detail' task.slug %}">
                        <h1>{{ task.name | upper }}</h1>
                        <p>Created on: {{task.date_added}}</p>
                        <p>{{ task.description | linebreaks | slice:":50" }}</p>
                    </a>
                </td>
            </tr>
        {% endfor %}
        </div>
        
    </table>
    <div class="form">
        <div>
            <form method="post" action=".">
                {% csrf_token %}
                {{ form.as_p }}
                <br />
                <input type="submit" name="submit" value="Add A Task"/>
            </form>
        </div>    
    </div>
</div>

<div id="related_task">
    {% if completed_list %}
    <h2 id="completed">COMPLETED TASKS</h2>
    <table id="related_table">
        <thead>
            <th><h1>Due Date</h1></td>
            <hr>
            <th><h1>Task</h1></td>
            <hr>
        </thead> 
        <tbody>
        {% for tasks in completed_list %}
            <tr>
                {% if tasks.slug != task.slug %}
                <td>
                    <p>
                        {% if tasks.status == "Completed" %}
                            <input type="checkbox" name="submit" value="Mark" checked/>
                        {% else %}
                            <input type="checkbox" name="submit" value="Mark"/>
                        {% endif %}
                        {{ task.due_date }}
                    </p><hr>
                </td>
                <td class="each_task">
                    <a href="{% url 'todo_app:task_detail' tasks.slug %}">
                        <h1>{{ tasks.name | upper }}</h1>
                        <p>Created on: {{tasks.date_added}}</p>
                        <p>{{ tasks.description | linebreaks | slice:":50" }}</p>
                    </a>
                </td>
                {% endif %}
            </tr>
        {% endfor %}
        </div>
    </table>
    {% else %}
    {% endif %}
</div>
<div id="related_task">
    {% if pending_list %}
    <h2 id="pending"> PENDING TASKS</h2>
    <table id="related_table">
        <thead>
            <th><h1>Due Date</h1></td>
            <hr>
            <th><h1>Task</h1></td>
            <hr>
        </thead>
        <tbody>
        {% for tasks in pending_list %}
            <tr>
                {% if tasks.slug != task.slug %}
                <td>
                    <p><input type="checkbox" name="submit" value="Mark"/></p><hr>
                </td>
                <td class="each_task">
                    <a href="{% url 'todo_app:task_detail' tasks.slug %}">
                        <h1>{{ tasks.name | upper }}</h1>
                        <p>Created on: {{tasks.date_added}}</p>
                        <p>{{ tasks.description | linebreaks | slice:":50" }}</p>
                    </a>
                </td>
                {% endif %}
            </tr>
        {% endfor %}
        </div>
        
    </table>
    {% else %}
    {% endif %}
</div>
{% endblock %}

templates/navbar.html
<div id="nav">
    <nav>
        <header>MY TODO LIST <em>Total no.: <strong>{{todo_item_count}}</strong></em></header>
        <ul>
            <li><a href="{% url 'todo_app:home' %}">All Task</a></li>
            <li><a href="#completed">Completed</a></li>
            <li><a href="#pending">Pending</a></li>
        </ul>
    </nav>
</div>

templates/task.html
{% extends "base.html" %}
{% block site_wrapper %}
{% include "navbar.html" %}
<div class="main">
    <div class="content">
        <h1>{{ task.name | upper }}
            {% if task.status == "Completed" %}
                <input type="checkbox" name="submit" value="Mark" checked/>
            {% else %}
                <input type="checkbox" name="submit" value="Mark"/>
            {% endif %}
        </h1>
        <p>Was created on: <em>{{task.date_added}}</em>, and will be Due on: <em>{{task.due_date}}</em></p>
        <br/><br/>
        <h3>Task Description</h3>
        <p>{{task.description | linebreaks }}</p>
        <form method="post" action="{% url 'todo_app:task_detail' task.slug %}" class="cart">
            {% csrf_token %}
            <input type="hidden" name="item_id" value="{{ task.id }}" />
            <input type="submit" name="submit" value="Remove" />
        </form>
        <form method="post" action="{% url 'todo_app:change_status' task.slug %}">
            {% csrf_token %}
            <input type="hidden" name="item_id" value="{{ task.id }}" />
            <input type="submit" name="submit" value="Completed" />
        </form>
    </div>
    
    <div class="form">
        <form method="post" action="{% url 'todo_app:task_detail' task.slug %}" class="cart">
            {% csrf_token %}
            <label for="title">Title:<input type="text" name="title" value="{{ task.name }}" /></label>
            <label for="description">Description:<input type="textarea" name="description" value="{{ task.description }}" /></label>
            <label for="due_date">Due Date:<input type="date" name="due_date" value="{{ task.due_date }}" /></label>
            <input type="hidden" name="item_id" value="{{ task.id }}" />
            
            <input type="submit" name="submit" value="Update" />
        </form>
    </div>
</div>    
<div id="related_task">
    {% if tasks %}
    {% else %}
        <h2>Other Tasks</h2>
    {% endif %}
    <table id="related_table">
        <thead>
            <th><h1>Due Date</h1></td>
            <hr>
            <th><h1>Task</h1></td>
            <hr>
        </thead>
        
        
        
        <tbody>
        {% for tasks in tasks %}
            <tr>
                {% if tasks.slug != task.slug %}
                <td><p>{{ tasks.due_date }}</p><hr></td>
                <td class="each_task">
                    <a href="{% url 'todo_app:task_detail' tasks.slug %}">
                        <h1>{{ tasks.name | upper }}</h1>
                        <p>Created on: {{tasks.date_added}}</p>
                        <p>{{ tasks.description | linebreaks | slice:":50" }}</p>
                    </a>
                </td>
                {% endif %}
            </tr>
        {% endfor %}
        </div>
        
    </table>
    
</div>    

{% endblock %}